server:
  port: 8889
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其它微服务
          enabled: true
      routes:
        - id: template
          # lb代表从注册中心获取服务
          uri: lb://coupon-template
          # 谓词工厂
          predicates:
            - Path=/template/**

        - id: distribution
          # lb代表从注册中心获取服务
          uri: lb://coupon-distribution
          # 谓词工厂
          predicates:
            - Path=/distribution/**

        - id: settlement
            # lb代表从注册中心获取服务
          uri: lb://coupon-settlement
            # 谓词工厂
          predicates:
            - Path=/settlement/**
        #            - TimeBetween=上午0:00,下午11:59
        #          filters:
        #            - PreLog=a,b
#  zipkin:
#    base-url: http://localhost:9411/
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

